/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AmbulanceRole;

import Business.AmbulanceService.AmbulanceService;
import Business.AmbulanceService.Service;
import Business.AmbulanceService.ServiceDirectory;
import userinterface.HospitalAdminRole.*;
import userinterface.CustomerRole.*;
import userinterface.SystemAdminWorkArea.*;
import Business.EcoSystem;
import Business.Hospital.Department.HospitalDepartment;
import Business.Hospital.Department.HospitalDepartmentDirectory;
import Business.Hospital.Hospital;
import Business.Staff.Sessions;
import Business.Staff.SessionsDirectory;
import Business.Staff.SessionsMedStaff;
import Business.Staff.Staff;
import Business.User.User;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.OrderItem;
import Business.WorkQueue.OrderList;
import Business.WorkQueue.WorkRequest;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import javax.swing.JPanel;

/**
 *
 * @author khushbu
 */
public class AmbulanceDashboard extends javax.swing.JPanel {

    /**
     * Creates new form AdminDashboard
     */
    private JPanel mainWorkArea;
    private EcoSystem ecosystem;
    private UserAccount userAccount;
//    private User user;
    private Hospital hospital;
    private AmbulanceService ambulanceService;
    private List<WorkRequest> workRequestList;

    public AmbulanceDashboard(JPanel mainWorkArea, EcoSystem ecosystem, UserAccount userAccount) {
        this.mainWorkArea = mainWorkArea;
        this.ecosystem = ecosystem;
        this.userAccount = userAccount;
        this.ambulanceService = (AmbulanceService) userAccount;
        initComponents();
        setData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boxStudentsCount = new javax.swing.JPanel();
        lblServices = new javax.swing.JLabel();
        lblIconStudent = new javax.swing.JLabel();
        lblOrders1 = new javax.swing.JLabel();
        boxStudentsCount2 = new javax.swing.JPanel();
        lblCompleted = new javax.swing.JLabel();
        lblIconStudent2 = new javax.swing.JLabel();
        lblUsers = new javax.swing.JLabel();
        boxCountCourse = new javax.swing.JPanel();
        lblRequests = new javax.swing.JLabel();
        lblIconCourse = new javax.swing.JLabel();
        lblShops = new javax.swing.JLabel();
        panelTopStudents = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tblHeaderTopStudents = new javax.swing.JPanel();
        lblRowOrdersName1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tblRowOrdersName1 = new javax.swing.JPanel();
        tblRowDeptName1 = new javax.swing.JLabel();
        tblRowDeptBed1 = new javax.swing.JLabel();
        tblRowDeptName2 = new javax.swing.JPanel();
        tblRowOrderName2 = new javax.swing.JLabel();
        tblRowDeptBed2 = new javax.swing.JLabel();
        tblRow2 = new javax.swing.JPanel();
        tblRowDeptName3 = new javax.swing.JLabel();
        tblRowDeptBed3 = new javax.swing.JLabel();
        boxCountCourse5 = new javax.swing.JPanel();
        lblPending = new javax.swing.JLabel();
        lblIconCourse5 = new javax.swing.JLabel();
        lblShops1 = new javax.swing.JLabel();
        boxStudentsCount4 = new javax.swing.JPanel();
        lblOxygen = new javax.swing.JLabel();
        lblIconStudent4 = new javax.swing.JLabel();
        lblUsers1 = new javax.swing.JLabel();
        boxStudentsCount5 = new javax.swing.JPanel();
        lblCancelled = new javax.swing.JLabel();
        lblIconStudent5 = new javax.swing.JLabel();
        lblOrders3 = new javax.swing.JLabel();
        panelTopStudents2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tblHeaderTopStudents1 = new javax.swing.JPanel();
        lblRowOrdersName2 = new javax.swing.JLabel();
        tblRowOrdersName2 = new javax.swing.JPanel();
        tblRowStaffName1 = new javax.swing.JLabel();
        tblRow6 = new javax.swing.JPanel();
        tblRowStaffName2 = new javax.swing.JLabel();
        tblRow7 = new javax.swing.JPanel();
        tblRowStaffName3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(243, 235, 255));

        boxStudentsCount.setBackground(new java.awt.Color(255, 255, 255));
        boxStudentsCount.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));

        lblServices.setBackground(new java.awt.Color(0, 153, 255));
        lblServices.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblServices.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblServices.setText("0");

        lblIconStudent.setBackground(new java.awt.Color(0, 153, 255));
        lblIconStudent.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblIconStudent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/student-dash.png"))); // NOI18N

        lblOrders1.setForeground(new java.awt.Color(102, 102, 102));
        lblOrders1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOrders1.setText("Services");

        javax.swing.GroupLayout boxStudentsCountLayout = new javax.swing.GroupLayout(boxStudentsCount);
        boxStudentsCount.setLayout(boxStudentsCountLayout);
        boxStudentsCountLayout.setHorizontalGroup(
            boxStudentsCountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boxStudentsCountLayout.createSequentialGroup()
                .addComponent(lblIconStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(boxStudentsCountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOrders1, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                    .addComponent(lblServices, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        boxStudentsCountLayout.setVerticalGroup(
            boxStudentsCountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boxStudentsCountLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblServices, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(lblOrders1)
                .addGap(20, 20, 20))
            .addComponent(lblIconStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        boxStudentsCount2.setBackground(new java.awt.Color(255, 255, 255));
        boxStudentsCount2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));

        lblCompleted.setBackground(new java.awt.Color(255, 255, 255));
        lblCompleted.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblCompleted.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCompleted.setText("0");

        lblIconStudent2.setBackground(new java.awt.Color(0, 153, 255));
        lblIconStudent2.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblIconStudent2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconStudent2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/student-dash.png"))); // NOI18N

        lblUsers.setForeground(new java.awt.Color(102, 102, 102));
        lblUsers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsers.setText("Completed Request");

        javax.swing.GroupLayout boxStudentsCount2Layout = new javax.swing.GroupLayout(boxStudentsCount2);
        boxStudentsCount2.setLayout(boxStudentsCount2Layout);
        boxStudentsCount2Layout.setHorizontalGroup(
            boxStudentsCount2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boxStudentsCount2Layout.createSequentialGroup()
                .addComponent(lblIconStudent2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(boxStudentsCount2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCompleted, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        boxStudentsCount2Layout.setVerticalGroup(
            boxStudentsCount2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boxStudentsCount2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblCompleted, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(lblUsers)
                .addGap(20, 20, 20))
            .addComponent(lblIconStudent2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        boxCountCourse.setBackground(new java.awt.Color(255, 255, 255));
        boxCountCourse.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        boxCountCourse.setPreferredSize(new java.awt.Dimension(209, 98));

        lblRequests.setBackground(new java.awt.Color(255, 255, 255));
        lblRequests.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblRequests.setForeground(new java.awt.Color(3, 80, 111));
        lblRequests.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRequests.setText("0");

        lblIconCourse.setBackground(new java.awt.Color(0, 153, 255));
        lblIconCourse.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblIconCourse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconCourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/courses-dashboard.png"))); // NOI18N

        lblShops.setForeground(new java.awt.Color(102, 102, 102));
        lblShops.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblShops.setText("Total Requests");

        javax.swing.GroupLayout boxCountCourseLayout = new javax.swing.GroupLayout(boxCountCourse);
        boxCountCourse.setLayout(boxCountCourseLayout);
        boxCountCourseLayout.setHorizontalGroup(
            boxCountCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boxCountCourseLayout.createSequentialGroup()
                .addComponent(lblIconCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(boxCountCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblShops, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(lblRequests, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        boxCountCourseLayout.setVerticalGroup(
            boxCountCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boxCountCourseLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblRequests, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(lblShops)
                .addGap(20, 20, 20))
            .addComponent(lblIconCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        panelTopStudents.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Ambulance Request");

        tblHeaderTopStudents.setBackground(new java.awt.Color(244, 249, 255));
        tblHeaderTopStudents.setForeground(new java.awt.Color(255, 255, 255));

        lblRowOrdersName1.setText("Name");

        jLabel4.setText("Status");

        javax.swing.GroupLayout tblHeaderTopStudentsLayout = new javax.swing.GroupLayout(tblHeaderTopStudents);
        tblHeaderTopStudents.setLayout(tblHeaderTopStudentsLayout);
        tblHeaderTopStudentsLayout.setHorizontalGroup(
            tblHeaderTopStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tblHeaderTopStudentsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRowOrdersName1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        tblHeaderTopStudentsLayout.setVerticalGroup(
            tblHeaderTopStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tblHeaderTopStudentsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tblHeaderTopStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRowOrdersName1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tblRowOrdersName1.setBackground(new java.awt.Color(255, 255, 255));
        tblRowOrdersName1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        tblRowOrdersName1.setForeground(new java.awt.Color(204, 204, 204));

        tblRowDeptName1.setText("NA");

        tblRowDeptBed1.setText("-");

        javax.swing.GroupLayout tblRowOrdersName1Layout = new javax.swing.GroupLayout(tblRowOrdersName1);
        tblRowOrdersName1.setLayout(tblRowOrdersName1Layout);
        tblRowOrdersName1Layout.setHorizontalGroup(
            tblRowOrdersName1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tblRowOrdersName1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tblRowDeptName1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tblRowDeptBed1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        tblRowOrdersName1Layout.setVerticalGroup(
            tblRowOrdersName1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tblRowOrdersName1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tblRowOrdersName1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tblRowDeptBed1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tblRowDeptName1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tblRowDeptName2.setBackground(new java.awt.Color(255, 255, 255));
        tblRowDeptName2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        tblRowDeptName2.setForeground(new java.awt.Color(204, 204, 204));

        tblRowOrderName2.setText("NA");

        tblRowDeptBed2.setText("-");

        javax.swing.GroupLayout tblRowDeptName2Layout = new javax.swing.GroupLayout(tblRowDeptName2);
        tblRowDeptName2.setLayout(tblRowDeptName2Layout);
        tblRowDeptName2Layout.setHorizontalGroup(
            tblRowDeptName2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tblRowDeptName2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tblRowOrderName2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tblRowDeptBed2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        tblRowDeptName2Layout.setVerticalGroup(
            tblRowDeptName2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tblRowDeptName2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tblRowDeptName2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tblRowDeptBed2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tblRowOrderName2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tblRow2.setBackground(new java.awt.Color(255, 255, 255));
        tblRow2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        tblRow2.setForeground(new java.awt.Color(204, 204, 204));

        tblRowDeptName3.setText("NA");

        tblRowDeptBed3.setText("-");

        javax.swing.GroupLayout tblRow2Layout = new javax.swing.GroupLayout(tblRow2);
        tblRow2.setLayout(tblRow2Layout);
        tblRow2Layout.setHorizontalGroup(
            tblRow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tblRow2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tblRowDeptName3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tblRowDeptBed3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        tblRow2Layout.setVerticalGroup(
            tblRow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tblRow2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tblRow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tblRowDeptBed3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tblRowDeptName3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelTopStudentsLayout = new javax.swing.GroupLayout(panelTopStudents);
        panelTopStudents.setLayout(panelTopStudentsLayout);
        panelTopStudentsLayout.setHorizontalGroup(
            panelTopStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTopStudentsLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelTopStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tblRow2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tblRowDeptName2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tblRowOrdersName1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tblHeaderTopStudents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        panelTopStudentsLayout.setVerticalGroup(
            panelTopStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTopStudentsLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(tblHeaderTopStudents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tblRowOrdersName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tblRowDeptName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tblRow2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        boxCountCourse5.setBackground(new java.awt.Color(255, 255, 255));
        boxCountCourse5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        boxCountCourse5.setPreferredSize(new java.awt.Dimension(209, 98));

        lblPending.setBackground(new java.awt.Color(255, 255, 255));
        lblPending.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblPending.setForeground(new java.awt.Color(3, 80, 111));
        lblPending.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPending.setText("0");

        lblIconCourse5.setBackground(new java.awt.Color(0, 153, 255));
        lblIconCourse5.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblIconCourse5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconCourse5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/courses-dashboard.png"))); // NOI18N

        lblShops1.setForeground(new java.awt.Color(102, 102, 102));
        lblShops1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblShops1.setText("Pending Request");

        javax.swing.GroupLayout boxCountCourse5Layout = new javax.swing.GroupLayout(boxCountCourse5);
        boxCountCourse5.setLayout(boxCountCourse5Layout);
        boxCountCourse5Layout.setHorizontalGroup(
            boxCountCourse5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boxCountCourse5Layout.createSequentialGroup()
                .addComponent(lblIconCourse5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(boxCountCourse5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblShops1, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(lblPending, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        boxCountCourse5Layout.setVerticalGroup(
            boxCountCourse5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boxCountCourse5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblPending, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(lblShops1)
                .addGap(20, 20, 20))
            .addComponent(lblIconCourse5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        boxStudentsCount4.setBackground(new java.awt.Color(255, 255, 255));
        boxStudentsCount4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));

        lblOxygen.setBackground(new java.awt.Color(255, 255, 255));
        lblOxygen.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblOxygen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOxygen.setText("0");

        lblIconStudent4.setBackground(new java.awt.Color(0, 153, 255));
        lblIconStudent4.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblIconStudent4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconStudent4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/student-dash.png"))); // NOI18N

        lblUsers1.setForeground(new java.awt.Color(102, 102, 102));
        lblUsers1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsers1.setText("Oxygen Available");

        javax.swing.GroupLayout boxStudentsCount4Layout = new javax.swing.GroupLayout(boxStudentsCount4);
        boxStudentsCount4.setLayout(boxStudentsCount4Layout);
        boxStudentsCount4Layout.setHorizontalGroup(
            boxStudentsCount4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boxStudentsCount4Layout.createSequentialGroup()
                .addComponent(lblIconStudent4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(boxStudentsCount4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsers1, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                    .addComponent(lblOxygen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        boxStudentsCount4Layout.setVerticalGroup(
            boxStudentsCount4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boxStudentsCount4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblOxygen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(lblUsers1)
                .addGap(20, 20, 20))
            .addComponent(lblIconStudent4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        boxStudentsCount5.setBackground(new java.awt.Color(255, 255, 255));
        boxStudentsCount5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));

        lblCancelled.setBackground(new java.awt.Color(0, 153, 255));
        lblCancelled.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblCancelled.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCancelled.setText("0");

        lblIconStudent5.setBackground(new java.awt.Color(0, 153, 255));
        lblIconStudent5.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblIconStudent5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconStudent5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/student-dash.png"))); // NOI18N

        lblOrders3.setForeground(new java.awt.Color(102, 102, 102));
        lblOrders3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOrders3.setText("Cancelled Request");

        javax.swing.GroupLayout boxStudentsCount5Layout = new javax.swing.GroupLayout(boxStudentsCount5);
        boxStudentsCount5.setLayout(boxStudentsCount5Layout);
        boxStudentsCount5Layout.setHorizontalGroup(
            boxStudentsCount5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boxStudentsCount5Layout.createSequentialGroup()
                .addComponent(lblIconStudent5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(boxStudentsCount5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOrders3, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                    .addComponent(lblCancelled, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        boxStudentsCount5Layout.setVerticalGroup(
            boxStudentsCount5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boxStudentsCount5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblCancelled, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(lblOrders3)
                .addGap(20, 20, 20))
            .addComponent(lblIconStudent5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        panelTopStudents2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Services");

        tblHeaderTopStudents1.setBackground(new java.awt.Color(244, 249, 255));
        tblHeaderTopStudents1.setForeground(new java.awt.Color(255, 255, 255));

        lblRowOrdersName2.setText("Name");

        javax.swing.GroupLayout tblHeaderTopStudents1Layout = new javax.swing.GroupLayout(tblHeaderTopStudents1);
        tblHeaderTopStudents1.setLayout(tblHeaderTopStudents1Layout);
        tblHeaderTopStudents1Layout.setHorizontalGroup(
            tblHeaderTopStudents1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tblHeaderTopStudents1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRowOrdersName2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        tblHeaderTopStudents1Layout.setVerticalGroup(
            tblHeaderTopStudents1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tblHeaderTopStudents1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRowOrdersName2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tblRowOrdersName2.setBackground(new java.awt.Color(255, 255, 255));
        tblRowOrdersName2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        tblRowOrdersName2.setForeground(new java.awt.Color(204, 204, 204));

        tblRowStaffName1.setText("NA");

        javax.swing.GroupLayout tblRowOrdersName2Layout = new javax.swing.GroupLayout(tblRowOrdersName2);
        tblRowOrdersName2.setLayout(tblRowOrdersName2Layout);
        tblRowOrdersName2Layout.setHorizontalGroup(
            tblRowOrdersName2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tblRowOrdersName2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tblRowStaffName1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        tblRowOrdersName2Layout.setVerticalGroup(
            tblRowOrdersName2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tblRowOrdersName2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tblRowStaffName1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tblRow6.setBackground(new java.awt.Color(255, 255, 255));
        tblRow6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        tblRow6.setForeground(new java.awt.Color(204, 204, 204));

        tblRowStaffName2.setText("NA");

        javax.swing.GroupLayout tblRow6Layout = new javax.swing.GroupLayout(tblRow6);
        tblRow6.setLayout(tblRow6Layout);
        tblRow6Layout.setHorizontalGroup(
            tblRow6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tblRow6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tblRowStaffName2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        tblRow6Layout.setVerticalGroup(
            tblRow6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tblRow6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tblRowStaffName2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tblRow7.setBackground(new java.awt.Color(255, 255, 255));
        tblRow7.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        tblRow7.setForeground(new java.awt.Color(204, 204, 204));

        tblRowStaffName3.setText("NA");

        javax.swing.GroupLayout tblRow7Layout = new javax.swing.GroupLayout(tblRow7);
        tblRow7.setLayout(tblRow7Layout);
        tblRow7Layout.setHorizontalGroup(
            tblRow7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tblRow7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tblRowStaffName3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        tblRow7Layout.setVerticalGroup(
            tblRow7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tblRow7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tblRowStaffName3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelTopStudents2Layout = new javax.swing.GroupLayout(panelTopStudents2);
        panelTopStudents2.setLayout(panelTopStudents2Layout);
        panelTopStudents2Layout.setHorizontalGroup(
            panelTopStudents2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTopStudents2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelTopStudents2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tblRow7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tblRow6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tblRowOrdersName2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tblHeaderTopStudents1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        panelTopStudents2Layout.setVerticalGroup(
            panelTopStudents2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTopStudents2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(tblHeaderTopStudents1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tblRowOrdersName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tblRow6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tblRow7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(boxStudentsCount5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(boxCountCourse5, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(boxStudentsCount4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(panelTopStudents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelTopStudents2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(boxStudentsCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(boxCountCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(boxStudentsCount2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boxCountCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxStudentsCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxStudentsCount2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boxCountCourse5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxStudentsCount5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxStudentsCount4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTopStudents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelTopStudents2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel boxCountCourse;
    private javax.swing.JPanel boxCountCourse5;
    private javax.swing.JPanel boxStudentsCount;
    private javax.swing.JPanel boxStudentsCount2;
    private javax.swing.JPanel boxStudentsCount4;
    private javax.swing.JPanel boxStudentsCount5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblCancelled;
    private javax.swing.JLabel lblCompleted;
    private javax.swing.JLabel lblIconCourse;
    private javax.swing.JLabel lblIconCourse5;
    private javax.swing.JLabel lblIconStudent;
    private javax.swing.JLabel lblIconStudent2;
    private javax.swing.JLabel lblIconStudent4;
    private javax.swing.JLabel lblIconStudent5;
    private javax.swing.JLabel lblOrders1;
    private javax.swing.JLabel lblOrders3;
    private javax.swing.JLabel lblOxygen;
    private javax.swing.JLabel lblPending;
    private javax.swing.JLabel lblRequests;
    private javax.swing.JLabel lblRowOrdersName1;
    private javax.swing.JLabel lblRowOrdersName2;
    private javax.swing.JLabel lblServices;
    private javax.swing.JLabel lblShops;
    private javax.swing.JLabel lblShops1;
    private javax.swing.JLabel lblUsers;
    private javax.swing.JLabel lblUsers1;
    private javax.swing.JPanel panelTopStudents;
    private javax.swing.JPanel panelTopStudents2;
    private javax.swing.JPanel tblHeaderTopStudents;
    private javax.swing.JPanel tblHeaderTopStudents1;
    private javax.swing.JPanel tblRow2;
    private javax.swing.JPanel tblRow6;
    private javax.swing.JPanel tblRow7;
    private javax.swing.JLabel tblRowDeptBed1;
    private javax.swing.JLabel tblRowDeptBed2;
    private javax.swing.JLabel tblRowDeptBed3;
    private javax.swing.JLabel tblRowDeptName1;
    private javax.swing.JPanel tblRowDeptName2;
    private javax.swing.JLabel tblRowDeptName3;
    private javax.swing.JLabel tblRowOrderName2;
    private javax.swing.JPanel tblRowOrdersName1;
    private javax.swing.JPanel tblRowOrdersName2;
    private javax.swing.JLabel tblRowStaffName1;
    private javax.swing.JLabel tblRowStaffName2;
    private javax.swing.JLabel tblRowStaffName3;
    // End of variables declaration//GEN-END:variables

    private void setData() {
        ServiceDirectory sd = ambulanceService.getServiceDirectory();

        int oxygen = 0;

        if (sd != null) {
            ArrayList<Service> serviceList = sd.getServiceList();
            if (serviceList != null) {

                lblServices.setText(String.valueOf(serviceList.size()));

                int len = serviceList.size() > 3 ? 3 : serviceList.size();

                for (int i = 0; i < len; i++) {
                    if (i == 0) {
                        tblRowStaffName1.setText(serviceList.get(i).getName());
                    } else if (i == 1) {
                        tblRowStaffName2.setText(serviceList.get(i).getName());
                    } else if (i == 2) {
                        tblRowStaffName3.setText(serviceList.get(i).getName());
                    }
                }

                for (Service s : serviceList) {
                    if (s.getOxygenAvailability().equalsIgnoreCase("yes")) {
                        oxygen++;
                    }
                }

                lblOxygen.setText(String.valueOf(oxygen));
            }
        }

        AmbulanceService amb = ecosystem.getAmbulanceDirectory().getAmbulanceServiceByUserName(userAccount.getUsername());

        if (amb != null) {
//            lblServices.setText(String.valueOf(amb.getServiceDirectory().getServiceList().size()));
            int completed = 0, cancelled = 0, pending = 0, count = 1, total = 0;
            for (Service s : amb.getServiceDirectory().getServiceList()) {
//                System.out.println(s);
                String status = s.getStatus();
                status = status.toUpperCase();

                if (s.getUser() != null) {
                    total++;
                    switch (status) {
                        case "COMPLETED":
                            completed++;

                            break;
                        case "CANCELLED":
                            cancelled++;

                            break;

                        default:
                            pending++;

                            break;
                    }

                    if (count == 1) {
                        tblRowDeptName1.setText(s.getCustomerName());
                        tblRowDeptBed1.setText(status);
                        count++;
                    } else if (count == 2) {
                        tblRowOrderName2.setText(s.getCustomerName());
                        tblRowDeptBed2.setText(status);
                        count++;
                    } else if (count == 3) {
                        tblRowDeptName3.setText(s.getCustomerName());
                        tblRowDeptBed3.setText(status);
                        count++;
                    }
                }
            }

            lblCompleted.setText(String.valueOf(completed));
            lblCancelled.setText(String.valueOf(cancelled));
            lblPending.setText(String.valueOf(pending));
            lblRequests.setText(String.valueOf(total));

            ecosystem.getTypeDirectory().getTypeList();
        }

//        HospitalDepartmentDirectory hdd = hospital.getDepartmentDirectory();
//
//        if (hdd != null) {
//
//            lblDept.setText(String.valueOf(hdd.getDepartmentList().size()));
//
//            int staff = 0, beds = 0, consultation = 0, deptCount = 1, staffCount = 1, doctors = 0;
//
//            int appointments = 0;
//
//            if (hdd.getDepartmentList() != null) {
//
//                for (HospitalDepartment hd : hdd.getDepartmentList()) {
//
//                    beds += hd.getNumberOfBeds();
//
//                    switch (deptCount) {
//                        case 1:
//                            tblRowDeptName1.setText(hd.getDepartmentName());
//                            tblRowDeptBed1.setText(String.valueOf(hd.getNumberOfBeds()));
//                            deptCount++;
//                            break;
//                        case 2:
//                            tblRowOrderName2.setText(hd.getDepartmentName());
//                            tblRowDeptBed2.setText(String.valueOf(hd.getNumberOfBeds()));
//                            deptCount++;
//                            break;
//                        case 3:
//                            tblRowDeptName3.setText(hd.getDepartmentName());
//                            tblRowDeptBed3.setText(String.valueOf(hd.getNumberOfBeds()));
//                            deptCount++;
//                            break;
//                        default:
//                            break;
//                    }
//
//                    if (hd.getStaffDirectory() != null && hd.getStaffDirectory().getStaffList() != null) {
//                        staff += hd.getStaffDirectory().getStaffList().size();
//                        for (Staff s : hd.getStaffDirectory().getStaffList()) {
//                            consultation += s.getConsultationDirectory().getSession().size();
//
//                            if (s.getDesignation().equalsIgnoreCase("DOCTOR")) {
//                                doctors++;
//                            }
//
//                            if (ecosystem.getWorkQueue() != null
//                                    && ecosystem.getWorkQueue().getStaffRequestList1(s, "USER-ORDER") != null) {
//                                appointments = ecosystem.getWorkQueue().getStaffRequestList1(s, "USER-ORDER").size();
//                            }
//
//                            switch (staffCount) {
//                                case 1:
//                                    tblRowStaffName1.setText(s.getName());
//                                    tblRowStaffDesig1.setText(s.getDesignation());
//
//                                    staffCount++;
//                                    break;
//                                case 2:
//                                    tblRowStaffName2.setText(s.getName());
//                                    tblRowStaffDesig2.setText(s.getDesignation());
//                                    staffCount++;
//                                    break;
//                                case 3:
//                                    tblRowStaffName3.setText(s.getName());
//                                    tblRowStaffDesig3.setText(s.getDesignation());
//                                    staffCount++;
//                                    break;
//                                default:
//                                    break;
//                            }
//                        }
//                    }
//                }
//
//                lblBeds.setText(String.valueOf(beds));
//                lblStaff.setText(String.valueOf(staff));
//                lblConsultations.setText(String.valueOf(consultation));
//                lblDoctors.setText(String.valueOf(doctors));
//                lblAppointments.setText(String.valueOf(appointments));
//            }
//        }
    }
}
