/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

/**
 *
 * @author khushbu
 */
public class LoginScreen extends javax.swing.JPanel {

    /**
     * Creates new form LoginScreen
     */
    public LoginScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanelContent = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        userNameJTextField = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        lblSignup = new javax.swing.JLabel();
        lblMemberSignup = new javax.swing.JLabel();
        imgLogin = new javax.swing.JLabel();

        setBackground(new java.awt.Color(3, 80, 111));
        setPreferredSize(new java.awt.Dimension(1270, 801));

        loginPanelContent.setBackground(new java.awt.Color(255, 255, 255));
        loginPanelContent.setPreferredSize(new java.awt.Dimension(635, 748));

        lblTitle.setBackground(new java.awt.Color(237, 255, 238));
        lblTitle.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(153, 153, 153));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitle.setText("Please login to continue!");

        lblUsername.setBackground(new java.awt.Color(249, 244, 244));
        lblUsername.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUsername.setText("Username :");

        userNameJTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        lblPassword.setBackground(new java.awt.Color(249, 244, 244));
        lblPassword.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPassword.setText("Password :");

        btnLogin.setBackground(new java.awt.Color(3, 80, 111));
        btnLogin.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("LOGIN");
        btnLogin.setBorder(null);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        lblSignup.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSignup.setText("Not a member ?");
        lblSignup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblSignupMousePressed(evt);
            }
        });

        lblMemberSignup.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblMemberSignup.setForeground(new java.awt.Color(3, 80, 111));
        lblMemberSignup.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMemberSignup.setText("SIGN UP NOW");
        lblMemberSignup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblMemberSignupMousePressed(evt);
            }
        });

        javax.swing.GroupLayout loginPanelContentLayout = new javax.swing.GroupLayout(loginPanelContent);
        loginPanelContent.setLayout(loginPanelContentLayout);
        loginPanelContentLayout.setHorizontalGroup(
            loginPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelContentLayout.createSequentialGroup()
                .addContainerGap(168, Short.MAX_VALUE)
                .addGroup(loginPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanelContentLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMemberSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(loginPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                        .addComponent(userNameJTextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                        .addComponent(txtPassword, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(139, 139, 139))
        );
        loginPanelContentLayout.setVerticalGroup(
            loginPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelContentLayout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(lblUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(loginPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSignup)
                    .addComponent(lblMemberSignup))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        imgLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/login--img.png"))); // NOI18N
        imgLogin.setBounds(new java.awt.Rectangle(0, 0, 100, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginPanelContent, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(imgLogin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed

        String userName = userNameJTextField.getText();
        char[] passwordCharArray = txtPassword.getPassword();
        String password = String.valueOf(passwordCharArray);

        if (!util.isStringInputValid(userName)) {
            //  JOptionPane.showMessageDialog(null, "Plesae enter valid user name");
            util.showErrorToast("Plesae enter valid user name");
            //            JOptionPane.showMessageDialog(this, "Plesae enter valid user name",
                //                    "Error", JOptionPane.ERROR_MESSAGE);
        } else if (!util.isStringInputValid(password)) {
            util.showErrorToast("Plesae enter valid password");
            //  JOptionPane.showMessageDialog(null, "Plesae enter valid password");
            //            JOptionPane.showMessageDialog(this, "Plesae enter valid password",
                //                    "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            userName = userName.toLowerCase();

            userAccount = system.getUserAccountDirectory().authenticateUser(userName, password);

            if (userAccount == null) {
                util.showErrorToast("Invalid credentials");
                //                JOptionPane.showMessageDialog(this, "Invalid credentials",
                    //                        "Error", JOptionPane.ERROR_MESSAGE);

                //                JOptionPane.showMessageDialog(null, "Invalid credentials");
            } else {
                userNameJTextField.setText("");
                txtPassword.setText("");
                changePanel(userAccount);
            }
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void lblSignupMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSignupMousePressed
        // TODO add your handling code here:
        toggleForm("SIGNUP");
    }//GEN-LAST:event_lblSignupMousePressed

    private void lblMemberSignupMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMemberSignupMousePressed
        // TODO add your handling code here:
        toggleForm("SIGNUP");
    }//GEN-LAST:event_lblMemberSignupMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel imgLogin;
    private javax.swing.JLabel lblMemberSignup;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblSignup;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel loginPanelContent;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField userNameJTextField;
    // End of variables declaration//GEN-END:variables
}
