/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CustomerRole;

import userinterface.SystemAdminWorkArea.*;
import Business.EcoSystem;
import Business.User.User;
import constants.Utils;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author khushbu
 */
public class AddMedicalProfilePanel extends javax.swing.JPanel {

    private JPanel mainWorkArea;
    private EcoSystem ecosystem;

    Utils util;

    DefaultTableModel model;
    private User user;
    private ArrayList<String> detailsList;
    Boolean flag = false;

    Boolean isUpdatePage = false;

    /**
     * Creates new form AddUniversity
     *
     * @param mainWorkArea
     * @param ecosystem
     * @param user
     * @param isUpdatePage
     */
    public AddMedicalProfilePanel(JPanel mainWorkArea, EcoSystem ecosystem, User user) throws ParseException {
        initComponents();
        this.mainWorkArea = mainWorkArea;
        this.ecosystem = ecosystem;
        this.user = user;
        this.isUpdatePage = isUpdatePage;
        util = new Utils();
        detailsList = new ArrayList<>();
        setData();
        managePersonalInformation();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        splitPanel = new javax.swing.JSplitPane();
        topPanel = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        lblUserAction = new javax.swing.JLabel();
        bottomPanel = new javax.swing.JPanel();
        managePersonalInfoPanel = new javax.swing.JPanel();
        iconDashboard = new javax.swing.JLabel();
        managePerosnalInfo = new javax.swing.JLabel();
        manageHealthPanel = new javax.swing.JPanel();
        iconHospital = new javax.swing.JLabel();
        manageHealth = new javax.swing.JLabel();
        manageMedicalConditionPanel = new javax.swing.JPanel();
        iconShop = new javax.swing.JLabel();
        manageMedicalCondition = new javax.swing.JLabel();
        formPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(249, 244, 244));
        setLayout(new java.awt.BorderLayout());

        splitPanel.setDividerLocation(70);
        splitPanel.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        topPanel.setBackground(new java.awt.Color(255, 255, 255));

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/back.png"))); // NOI18N
        btnBack.setText("Back");
        btnBack.setToolTipText("View university list");
        btnBack.setActionCommand("University");
        btnBack.setAlignmentY(0.0F);
        btnBack.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true)));
        btnBack.setBorderPainted(false);
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnBack.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnBack.setIconTextGap(10);
        btnBack.setMargin(new java.awt.Insets(10, 5, 0, 2));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblUserAction.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblUserAction.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserAction.setText("User Profile");
        lblUserAction.setToolTipText("Add Department");

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(185, 185, 185)
                .addComponent(lblUserAction, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(440, Short.MAX_VALUE))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserAction, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        splitPanel.setTopComponent(topPanel);

        bottomPanel.setBackground(new java.awt.Color(243, 241, 249));

        managePersonalInfoPanel.setBackground(new java.awt.Color(3, 80, 111));
        managePersonalInfoPanel.setToolTipText("Manage Personal Information");
        managePersonalInfoPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        managePersonalInfoPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                managePersonalInfoPanelMousePressed(evt);
            }
        });

        iconDashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dinner.png"))); // NOI18N

        managePerosnalInfo.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        managePerosnalInfo.setForeground(new java.awt.Color(255, 255, 255));
        managePerosnalInfo.setText("Personal Information");
        managePerosnalInfo.setToolTipText("Dashboard");
        managePerosnalInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                managePerosnalInfoMousePressed(evt);
            }
        });

        javax.swing.GroupLayout managePersonalInfoPanelLayout = new javax.swing.GroupLayout(managePersonalInfoPanel);
        managePersonalInfoPanel.setLayout(managePersonalInfoPanelLayout);
        managePersonalInfoPanelLayout.setHorizontalGroup(
            managePersonalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(managePersonalInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(managePerosnalInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        managePersonalInfoPanelLayout.setVerticalGroup(
            managePersonalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(managePersonalInfoPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(managePersonalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(iconDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(managePerosnalInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5))
        );

        manageHealthPanel.setBackground(new java.awt.Color(3, 80, 111));
        manageHealthPanel.setToolTipText("Manage Health Profile");
        manageHealthPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageHealthPanel.setPreferredSize(new java.awt.Dimension(242, 53));
        manageHealthPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                manageHealthPanelMousePressed(evt);
            }
        });

        iconHospital.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconHospital.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dinner.png"))); // NOI18N

        manageHealth.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        manageHealth.setForeground(new java.awt.Color(255, 255, 255));
        manageHealth.setText("Health Profile");
        manageHealth.setToolTipText("Hospital");
        manageHealth.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                manageHealthMousePressed(evt);
            }
        });

        javax.swing.GroupLayout manageHealthPanelLayout = new javax.swing.GroupLayout(manageHealthPanel);
        manageHealthPanel.setLayout(manageHealthPanelLayout);
        manageHealthPanelLayout.setHorizontalGroup(
            manageHealthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageHealthPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconHospital, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageHealth, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        manageHealthPanelLayout.setVerticalGroup(
            manageHealthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageHealthPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(manageHealthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(iconHospital, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(manageHealth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5))
        );

        manageMedicalConditionPanel.setBackground(new java.awt.Color(3, 80, 111));
        manageMedicalConditionPanel.setToolTipText("Manage Medical Condition");
        manageMedicalConditionPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageMedicalConditionPanel.setPreferredSize(new java.awt.Dimension(242, 53));
        manageMedicalConditionPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                manageMedicalConditionPanelMousePressed(evt);
            }
        });

        iconShop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconShop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dinner.png"))); // NOI18N

        manageMedicalCondition.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        manageMedicalCondition.setForeground(new java.awt.Color(255, 255, 255));
        manageMedicalCondition.setText("Medical Conditions");
        manageMedicalCondition.setToolTipText("Shop");
        manageMedicalCondition.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                manageMedicalConditionMousePressed(evt);
            }
        });

        javax.swing.GroupLayout manageMedicalConditionPanelLayout = new javax.swing.GroupLayout(manageMedicalConditionPanel);
        manageMedicalConditionPanel.setLayout(manageMedicalConditionPanelLayout);
        manageMedicalConditionPanelLayout.setHorizontalGroup(
            manageMedicalConditionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageMedicalConditionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconShop, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageMedicalCondition, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        manageMedicalConditionPanelLayout.setVerticalGroup(
            manageMedicalConditionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageMedicalConditionPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(manageMedicalConditionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(iconShop, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(manageMedicalCondition, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5))
        );

        formPanel.setBackground(new java.awt.Color(243, 241, 249));
        formPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout bottomPanelLayout = new javax.swing.GroupLayout(bottomPanel);
        bottomPanel.setLayout(bottomPanelLayout);
        bottomPanelLayout.setHorizontalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomPanelLayout.createSequentialGroup()
                .addGap(0, 216, Short.MAX_VALUE)
                .addComponent(managePersonalInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(manageHealthPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(manageMedicalConditionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bottomPanelLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(formPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );
        bottomPanelLayout.setVerticalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(managePersonalInfoPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageMedicalConditionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageHealthPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(formPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                .addContainerGap())
        );

        splitPanel.setRightComponent(bottomPanel);

        add(splitPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    public void setFields(Boolean bool) {

    }

    private void setData() throws ParseException {

    }

    private void backAction() {
        mainWorkArea.remove(this);
        Component[] componentArray = mainWorkArea.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageUserPanel manageUserPanel = (ManageUserPanel) component;

        manageUserPanel.refreshTable();

        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.previous(mainWorkArea);
    }

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // back btn logic
        backAction();
    }//GEN-LAST:event_btnBackActionPerformed

    private void managePerosnalInfoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_managePerosnalInfoMousePressed
        try {
            managePersonalInformation();
        } catch (ParseException ex) {
            Logger.getLogger(AddMedicalProfilePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_managePerosnalInfoMousePressed

    private void managePersonalInfoPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_managePersonalInfoPanelMousePressed
        try {
            // TODO add your handling code here:
            managePersonalInformation();
        } catch (ParseException ex) {
            Logger.getLogger(AddMedicalProfilePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_managePersonalInfoPanelMousePressed

    private void manageHealthMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageHealthMousePressed
        try {
            // TODO add your handling code here:
            manageHealthInformation();
        } catch (ParseException ex) {
            Logger.getLogger(AddMedicalProfilePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_manageHealthMousePressed

    private void manageHealthPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageHealthPanelMousePressed
        try {
            // TODO add your handling code here:
            manageHealthInformation();
        } catch (ParseException ex) {
            Logger.getLogger(AddMedicalProfilePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_manageHealthPanelMousePressed

    private void manageMedicalConditionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageMedicalConditionMousePressed
        // TODO add your handling code here:
        manageMedicalInformation();
    }//GEN-LAST:event_manageMedicalConditionMousePressed

    private void manageMedicalConditionPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageMedicalConditionPanelMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_manageMedicalConditionPanelMousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JButton btnBack;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JPanel formPanel;
    private javax.swing.JLabel iconDashboard;
    private javax.swing.JLabel iconHospital;
    private javax.swing.JLabel iconShop;
    private javax.swing.JLabel lblUserAction;
    private javax.swing.JLabel manageHealth;
    private javax.swing.JPanel manageHealthPanel;
    private javax.swing.JLabel manageMedicalCondition;
    private javax.swing.JPanel manageMedicalConditionPanel;
    private javax.swing.JLabel managePerosnalInfo;
    private javax.swing.JPanel managePersonalInfoPanel;
    private javax.swing.JSplitPane splitPanel;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables

    private void managePersonalInformation() throws ParseException {

//        formPanel
        changeBtnBgs("personal");
        AddPersonalInfoPanel addPersonalInfoPanel = new AddPersonalInfoPanel(formPanel, ecosystem, user);

        formPanel.add("addPersonalInfoPanel", addPersonalInfoPanel);
        CardLayout layout = (CardLayout) formPanel.getLayout();
        layout.next(formPanel);
    }
    private void manageHealthInformation() throws ParseException {

//        formPanel
        changeBtnBgs("health");
        AddHealthInfoPanel addHealthInfoPanel = new AddHealthInfoPanel(formPanel, ecosystem, user);

        formPanel.add("addLifeStyleInfoPanel", addHealthInfoPanel);
        CardLayout layout = (CardLayout) formPanel.getLayout();
        layout.next(formPanel);
    }
        private void manageMedicalInformation() {

//        formPanel
        changeBtnBgs("medical");
        AddMedicalInfoPanel addMedicalInfoPanel = new AddMedicalInfoPanel(formPanel, ecosystem, user);

        formPanel.add("addMedicalInfoPanel", addMedicalInfoPanel);
        CardLayout layout = (CardLayout) formPanel.getLayout();
        layout.next(formPanel);
    }
    private void changeBtnBgs(String type) {
        
        Color activeColor = Color.getHSBColor(3, 80, 111);
        Color notActiveColor = Color.WHITE;
        //Color.getColor("03506F");
        Color activeTxtColor = Color.WHITE;
        Color nonActiveTxtColor = Color.BLACK;

        managePersonalInfoPanel.setBackground(notActiveColor);
        manageMedicalConditionPanel.setBackground(notActiveColor);
        manageHealthPanel.setBackground(notActiveColor);

        managePerosnalInfo.setForeground(nonActiveTxtColor);
        manageHealth.setForeground(nonActiveTxtColor);
        manageMedicalCondition.setForeground(nonActiveTxtColor);

        if ("personal".equalsIgnoreCase(type)) {
            managePersonalInfoPanel.setBackground(activeColor);
            managePerosnalInfo.setForeground(activeTxtColor);
        } else if ("health".equalsIgnoreCase(type)) {
            manageHealthPanel.setBackground(activeColor);
            manageHealth.setForeground(activeTxtColor);
        } else if ("medical".equalsIgnoreCase(type)) {
            manageMedicalConditionPanel.setBackground(activeColor);
            manageMedicalCondition.setForeground(activeTxtColor);
        }
    }
}
