/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CustomerRole;

import userinterface.SystemAdminWorkArea.*;
import Business.EcoSystem;
import Business.Staff.SessionsMedStaff;
import Business.Staff.Staff;
import Business.User.TempTable.ConsultData;
import Business.User.User;
import constants.Utils;

import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author khushbu
 */
public class ConsultationFormPatient extends javax.swing.JPanel {

    private JPanel mainWorkArea;
    private EcoSystem ecosystem;

    Utils util;

    DefaultTableModel model;
    private User user;
    ArrayList<ConsultData> consultDatalist;
    Boolean isUpdatePage = false;
    private String selectedValue;
    Boolean isNone = false;
    private SessionsMedStaff sess;
    private Staff staff;

    public ConsultationFormPatient(JPanel mainWorkArea, EcoSystem ecosystem,User user, Staff staff, SessionsMedStaff sess) {
        initComponents();
        this.mainWorkArea = mainWorkArea;
        this.ecosystem = ecosystem;
        this.isUpdatePage = isUpdatePage;
        util = new Utils();
        this.user = user;
        this.staff = staff;
        this.sess = sess;
        consultDatalist= new ArrayList<>();
        setData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        splitPanel = new javax.swing.JSplitPane();
        topPanel = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        lblUserAction = new javax.swing.JLabel();
        bottomPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        jComboBoxDisease = new javax.swing.JComboBox<>();
        lblChoose = new javax.swing.JLabel();
        jOuterPanel = new javax.swing.JPanel();
        jInnerPanel = new javax.swing.JPanel();
        lblSeverity = new javax.swing.JLabel();
        jComboBoxSeverity = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxDays = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtcomment = new javax.swing.JTextField();
        btnSignup1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(249, 244, 244));
        setLayout(new java.awt.BorderLayout());

        splitPanel.setDividerLocation(70);
        splitPanel.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        topPanel.setBackground(new java.awt.Color(255, 255, 255));

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/back.png"))); // NOI18N
        btnBack.setText("Back");
        btnBack.setToolTipText("View university list");
        btnBack.setActionCommand("University");
        btnBack.setAlignmentY(0.0F);
        btnBack.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true)));
        btnBack.setBorderPainted(false);
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnBack.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnBack.setIconTextGap(10);
        btnBack.setMargin(new java.awt.Insets(10, 5, 0, 2));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblUserAction.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblUserAction.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserAction.setText("Current Medical Record");
        lblUserAction.setToolTipText("Add Department");

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(185, 185, 185)
                .addComponent(lblUserAction, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(429, Short.MAX_VALUE))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserAction, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        splitPanel.setTopComponent(topPanel);

        bottomPanel.setBackground(new java.awt.Color(243, 241, 249));

        jPanel1.setBackground(new java.awt.Color(243, 241, 249));

        btnAdd.setBackground(new java.awt.Color(3, 80, 111));
        btnAdd.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/save.png"))); // NOI18N
        btnAdd.setText("Add");
        btnAdd.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jComboBoxDisease.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Other", "Fever", "Cough", "Body Pain", "Breathing Issue", "None", " " }));
        jComboBoxDisease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDiseaseActionPerformed(evt);
            }
        });

        lblChoose.setText("Select Disease or Symptoms:");

        lblSeverity.setText("Select Severity:");

        jComboBoxSeverity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSeverityActionPerformed(evt);
            }
        });

        jLabel2.setText("Select Days");

        jComboBoxDays.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "0-2 days", "2-5 days", "5-8 days", "8-10 days", "more than 10 days" }));

        javax.swing.GroupLayout jInnerPanelLayout = new javax.swing.GroupLayout(jInnerPanel);
        jInnerPanel.setLayout(jInnerPanelLayout);
        jInnerPanelLayout.setHorizontalGroup(
            jInnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInnerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblSeverity, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(jComboBoxSeverity, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jInnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jComboBoxDays, 0, 128, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jInnerPanelLayout.setVerticalGroup(
            jInnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInnerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jInnerPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxDays, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInnerPanelLayout.createSequentialGroup()
                        .addComponent(lblSeverity, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxSeverity, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jLabel3.setText("AddComment");

        javax.swing.GroupLayout jOuterPanelLayout = new javax.swing.GroupLayout(jOuterPanel);
        jOuterPanel.setLayout(jOuterPanelLayout);
        jOuterPanelLayout.setHorizontalGroup(
            jOuterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jOuterPanelLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jOuterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtcomment, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jInnerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jOuterPanelLayout.setVerticalGroup(
            jOuterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jOuterPanelLayout.createSequentialGroup()
                .addComponent(jInnerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtcomment, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        btnSignup1.setBackground(new java.awt.Color(3, 80, 111));
        btnSignup1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnSignup1.setForeground(new java.awt.Color(255, 255, 255));
        btnSignup1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/save.png"))); // NOI18N
        btnSignup1.setText("Submit");
        btnSignup1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnSignup1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignup1ActionPerformed(evt);
            }
        });

        listTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Severity or range", "Number of days", "Comment"
            }
        ));
        jScrollPane1.setViewportView(listTable);

        jLabel1.setText("List of symptoms or disease");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(lblChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jOuterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jComboBoxDisease, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSignup1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(157, 157, 157))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxDisease, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jOuterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(315, 315, 315)
                        .addComponent(btnSignup1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bottomPanelLayout = new javax.swing.GroupLayout(bottomPanel);
        bottomPanel.setLayout(bottomPanelLayout);
        bottomPanelLayout.setHorizontalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomPanelLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(153, Short.MAX_VALUE))
        );
        bottomPanelLayout.setVerticalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        splitPanel.setRightComponent(bottomPanel);

        add(splitPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

private void setData(){
    String st = jComboBoxDisease.getSelectedItem().toString();
    if(st.toLowerCase().equals("none")){
        jComboBoxDays.setEnabled(false);
        jComboBoxSeverity.setEnabled(false);
        txtcomment.setEnabled(false);
        btnAdd.setEnabled(false);
        listTable.setEnabled(false);
    }else{
        jComboBoxDays.setEnabled(true);
        jComboBoxSeverity.setEnabled(true);
        txtcomment.setEnabled(true);
        btnAdd.setEnabled(true);
        listTable.setEnabled(true);
    }
    if(st.toLowerCase().equals("fever")){
        lblSeverity.setText("Range in Degree F");
        jComboBoxSeverity.removeAllItems();
        List<String> rangeList = Arrays.asList("Select","Low","Medium","High","99-100","100-101","101-102","102-103","103-104","104<");      
            for (String i:rangeList) {
                jComboBoxSeverity.addItem(i);
                }
    }else{
        lblSeverity.setText("Select Severity");
        jComboBoxSeverity.removeAllItems();
        List<String> newList = Arrays.asList("Select","Low","Medium","High"); 
        for (String i:newList) {
                jComboBoxSeverity.addItem(i);
                }
    }
}

    private void backAction() {
        mainWorkArea.remove(this);
        Component[] componentArray = mainWorkArea.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageUserPanel manageUserPanel = (ManageUserPanel) component;

        manageUserPanel.refreshTable();

        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.previous(mainWorkArea);
    }

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // back btn logic
        backAction();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String disease = jComboBoxDisease.getSelectedItem().toString(),
                severity = jComboBoxSeverity.getSelectedItem().toString(),
                days = jComboBoxDays.getSelectedItem().toString();
        String comments = txtcomment.getText();
        if(!util.isStringInputValid(comments)){
            util.showErrorToast("Please enter valid comments");
        }else if(disease.toLowerCase().equals("none")){
            isNone = true;
        } else if(days.toLowerCase().equals("Please select valid days")){
             util.showErrorToast("Please select valid severity level");
        } else{
        ConsultData dt = new ConsultData(disease,severity,days,comments);
        consultDatalist.add(dt);
        }
        populateViewTable();
        txtcomment.setText("");
        jComboBoxDisease.setSelectedItem("Other");
        jComboBoxDays.setSelectedItem("Select");
        jComboBoxSeverity.setSelectedItem("Select");
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnSignup1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignup1ActionPerformed
        // TODO add your handling code here:
        for(ConsultData cd: consultDatalist){
            if(cd.getDisease().toLowerCase().equals("fever")){
                user.getConsultationForm().setFever(cd.getDisease());
                user.getConsultationForm().setFeverRange(cd.getSeverity());
                user.getConsultationForm().setFeverDays(cd.getDays());
                user.getConsultationForm().setFeverMessage(cd.getComments());
            } else if(cd.getDisease().toLowerCase().equals("body pain")){
                user.getConsultationForm().setBodyPain(cd.getDisease());
                user.getConsultationForm().setBodyPainSeverity(cd.getSeverity());
                user.getConsultationForm().setBodyPainDays(cd.getDays());
                user.getConsultationForm().setBodyPainMessage(cd.getComments());
            } else if(cd.getDisease().toLowerCase().equals("cough")){
                user.getConsultationForm().setCough(cd.getDisease());
                user.getConsultationForm().setCoughSeverity(cd.getSeverity());
                user.getConsultationForm().setCoughDays(cd.getDays());
                user.getConsultationForm().setCoughMessage(cd.getComments());
            }else if(cd.getDisease().toLowerCase().equals("breathing issue")){
                user.getConsultationForm().setBreathingIssue(cd.getDisease());
                user.getConsultationForm().setBreathingSeverity(cd.getSeverity());
                user.getConsultationForm().setBreathingDays(cd.getDays());
                user.getConsultationForm().setBreathingMessage(cd.getComments());
            }else if(cd.getDisease().toLowerCase().equals("other")){
                user.getConsultationForm().setOther(cd.getDisease());
                user.getConsultationForm().setOtherRange(cd.getSeverity());
                user.getConsultationForm().setOtherDays(cd.getDays());
                user.getConsultationForm().setOtherMessage(cd.getComments());
            }
        }
                    staff.getConsultationDirectory().addSession(sess);
                    user.getConsultationSessions().addSession(sess);
                    staff.getSessionDirectory().removeSession(sess);
                    JOptionPane.showMessageDialog(this, "Your Consultation with "+staff.getName() +" Booked successfully",
                    "Success", JOptionPane.INFORMATION_MESSAGE);
                    goToManageUserConsultationPage();
                    
    }//GEN-LAST:event_btnSignup1ActionPerformed

    private void jComboBoxDiseaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDiseaseActionPerformed
        // TODO add your handling code here:
        String selected = jComboBoxDisease.getSelectedItem().toString();
        setData();
    }//GEN-LAST:event_jComboBoxDiseaseActionPerformed

    private void jComboBoxSeverityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSeverityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSeverityActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSignup1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> jComboBoxDays;
    private javax.swing.JComboBox<String> jComboBoxDisease;
    private javax.swing.JComboBox<String> jComboBoxSeverity;
    private javax.swing.JPanel jInnerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jOuterPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblChoose;
    private javax.swing.JLabel lblSeverity;
    private javax.swing.JLabel lblUserAction;
    private javax.swing.JTable listTable;
    private javax.swing.JSplitPane splitPanel;
    private javax.swing.JPanel topPanel;
    private javax.swing.JTextField txtcomment;
    // End of variables declaration//GEN-END:variables
     public void populateViewTable(){
        DefaultTableModel model = (DefaultTableModel) listTable.getModel();
        model.setRowCount(0);
            for(ConsultData st: consultDatalist){
                Object[] row = new Object[4];
                row[0] = st.getDisease();
                row[1] = st.getSeverity();
                row[2] = st.getDays();
                row[3] = st.getComments();
                model.addRow(row);
            }
     }
     private void goToManageUserConsultationPage(){
            ManageUserConsultationPanel bookConsultationPanel = new ManageUserConsultationPanel(mainWorkArea, ecosystem, user);
            mainWorkArea.add("bookConsultationPanel", bookConsultationPanel);
            CardLayout layout = (CardLayout) mainWorkArea.getLayout();
            layout.next(mainWorkArea);
    }
}
