/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.HospitalAdminRole;

import userinterface.CustomerRole.*;
import userinterface.SystemAdminWorkArea.*;
import Business.EcoSystem;
import Business.Hospital.Department.HospitalDepartment;
import Business.Hospital.Department.HospitalDepartmentDirectory;
import Business.Hospital.Hospital;
import Business.Staff.Sessions;
import Business.Staff.SessionsDirectory;
import Business.Staff.SessionsMedStaff;
import Business.Staff.Staff;
import Business.User.User;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.OrderItem;
import Business.WorkQueue.OrderList;
import Business.WorkQueue.WorkRequest;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import javax.swing.JPanel;

/**
 *
 * @author khushbu
 */
public class HospitalDashboard extends javax.swing.JPanel {

    /**
     * Creates new form AdminDashboard
     */
    private JPanel mainWorkArea;
    private EcoSystem ecosystem;
    private UserAccount userAccount;
//    private User user;
    private Hospital hospital;
    private List<WorkRequest> workRequestList;

    public HospitalDashboard(JPanel mainWorkArea, EcoSystem ecosystem, UserAccount userAccount) {
        this.mainWorkArea = mainWorkArea;
        this.ecosystem = ecosystem;
        this.userAccount = userAccount;
        this.hospital = (Hospital) userAccount;
        initComponents();
        setData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boxStudentsCount = new javax.swing.JPanel();
        lblDept = new javax.swing.JLabel();
        lblIconStudent = new javax.swing.JLabel();
        lblOrders1 = new javax.swing.JLabel();
        boxStudentsCount2 = new javax.swing.JPanel();
        lblBeds = new javax.swing.JLabel();
        lblIconStudent2 = new javax.swing.JLabel();
        lblUsers = new javax.swing.JLabel();
        boxCountCourse = new javax.swing.JPanel();
        lblStaff = new javax.swing.JLabel();
        lblIconCourse = new javax.swing.JLabel();
        lblShops = new javax.swing.JLabel();
        panelTopStudents = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tblHeaderTopStudents = new javax.swing.JPanel();
        lblRowOrdersName1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tblRowOrdersName1 = new javax.swing.JPanel();
        tblRowDeptName1 = new javax.swing.JLabel();
        tblRowDeptBed1 = new javax.swing.JLabel();
        tblRowDeptName2 = new javax.swing.JPanel();
        tblRowOrderName2 = new javax.swing.JLabel();
        tblRowDeptBed2 = new javax.swing.JLabel();
        tblRow2 = new javax.swing.JPanel();
        tblRowDeptName3 = new javax.swing.JLabel();
        tblRowDeptBed3 = new javax.swing.JLabel();
        boxCountCourse5 = new javax.swing.JPanel();
        lblAppointments = new javax.swing.JLabel();
        lblIconCourse5 = new javax.swing.JLabel();
        lblShops1 = new javax.swing.JLabel();
        boxStudentsCount4 = new javax.swing.JPanel();
        lblConsultations = new javax.swing.JLabel();
        lblIconStudent4 = new javax.swing.JLabel();
        lblUsers1 = new javax.swing.JLabel();
        boxStudentsCount5 = new javax.swing.JPanel();
        lblDoctors = new javax.swing.JLabel();
        lblIconStudent5 = new javax.swing.JLabel();
        lblOrders3 = new javax.swing.JLabel();
        panelTopStudents2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tblHeaderTopStudents1 = new javax.swing.JPanel();
        lblRowOrdersName2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tblRowOrdersName2 = new javax.swing.JPanel();
        tblRowStaffName1 = new javax.swing.JLabel();
        tblRowStaffDesig1 = new javax.swing.JLabel();
        tblRow6 = new javax.swing.JPanel();
        tblRowStaffName2 = new javax.swing.JLabel();
        tblRowStaffDesig2 = new javax.swing.JLabel();
        tblRow7 = new javax.swing.JPanel();
        tblRowStaffName3 = new javax.swing.JLabel();
        tblRowStaffDesig3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(243, 235, 255));

        boxStudentsCount.setBackground(new java.awt.Color(255, 255, 255));
        boxStudentsCount.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));

        lblDept.setBackground(new java.awt.Color(0, 153, 255));
        lblDept.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblDept.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDept.setText("0");

        lblIconStudent.setBackground(new java.awt.Color(0, 153, 255));
        lblIconStudent.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblIconStudent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/student-dash.png"))); // NOI18N

        lblOrders1.setForeground(new java.awt.Color(102, 102, 102));
        lblOrders1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOrders1.setText("Departments");

        javax.swing.GroupLayout boxStudentsCountLayout = new javax.swing.GroupLayout(boxStudentsCount);
        boxStudentsCount.setLayout(boxStudentsCountLayout);
        boxStudentsCountLayout.setHorizontalGroup(
            boxStudentsCountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boxStudentsCountLayout.createSequentialGroup()
                .addComponent(lblIconStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(boxStudentsCountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOrders1, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(lblDept, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        boxStudentsCountLayout.setVerticalGroup(
            boxStudentsCountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boxStudentsCountLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblDept, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(lblOrders1)
                .addGap(20, 20, 20))
            .addComponent(lblIconStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        boxStudentsCount2.setBackground(new java.awt.Color(255, 255, 255));
        boxStudentsCount2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));

        lblBeds.setBackground(new java.awt.Color(255, 255, 255));
        lblBeds.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblBeds.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBeds.setText("0");

        lblIconStudent2.setBackground(new java.awt.Color(0, 153, 255));
        lblIconStudent2.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblIconStudent2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconStudent2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/student-dash.png"))); // NOI18N

        lblUsers.setForeground(new java.awt.Color(102, 102, 102));
        lblUsers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsers.setText("Beds");

        javax.swing.GroupLayout boxStudentsCount2Layout = new javax.swing.GroupLayout(boxStudentsCount2);
        boxStudentsCount2.setLayout(boxStudentsCount2Layout);
        boxStudentsCount2Layout.setHorizontalGroup(
            boxStudentsCount2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boxStudentsCount2Layout.createSequentialGroup()
                .addComponent(lblIconStudent2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(boxStudentsCount2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsers, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(lblBeds, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        boxStudentsCount2Layout.setVerticalGroup(
            boxStudentsCount2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boxStudentsCount2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblBeds, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(lblUsers)
                .addGap(20, 20, 20))
            .addComponent(lblIconStudent2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        boxCountCourse.setBackground(new java.awt.Color(255, 255, 255));
        boxCountCourse.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        boxCountCourse.setPreferredSize(new java.awt.Dimension(209, 98));

        lblStaff.setBackground(new java.awt.Color(255, 255, 255));
        lblStaff.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblStaff.setForeground(new java.awt.Color(3, 80, 111));
        lblStaff.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStaff.setText("0");

        lblIconCourse.setBackground(new java.awt.Color(0, 153, 255));
        lblIconCourse.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblIconCourse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconCourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/courses-dashboard.png"))); // NOI18N

        lblShops.setForeground(new java.awt.Color(102, 102, 102));
        lblShops.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblShops.setText("Staff");

        javax.swing.GroupLayout boxCountCourseLayout = new javax.swing.GroupLayout(boxCountCourse);
        boxCountCourse.setLayout(boxCountCourseLayout);
        boxCountCourseLayout.setHorizontalGroup(
            boxCountCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boxCountCourseLayout.createSequentialGroup()
                .addComponent(lblIconCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(boxCountCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblShops, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(lblStaff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        boxCountCourseLayout.setVerticalGroup(
            boxCountCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boxCountCourseLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblStaff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(lblShops)
                .addGap(20, 20, 20))
            .addComponent(lblIconCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        panelTopStudents.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Departments");

        tblHeaderTopStudents.setBackground(new java.awt.Color(244, 249, 255));
        tblHeaderTopStudents.setForeground(new java.awt.Color(255, 255, 255));

        lblRowOrdersName1.setText("Name");

        jLabel4.setText("Beds");

        javax.swing.GroupLayout tblHeaderTopStudentsLayout = new javax.swing.GroupLayout(tblHeaderTopStudents);
        tblHeaderTopStudents.setLayout(tblHeaderTopStudentsLayout);
        tblHeaderTopStudentsLayout.setHorizontalGroup(
            tblHeaderTopStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tblHeaderTopStudentsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRowOrdersName1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        tblHeaderTopStudentsLayout.setVerticalGroup(
            tblHeaderTopStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tblHeaderTopStudentsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tblHeaderTopStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRowOrdersName1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tblRowOrdersName1.setBackground(new java.awt.Color(255, 255, 255));
        tblRowOrdersName1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        tblRowOrdersName1.setForeground(new java.awt.Color(204, 204, 204));

        tblRowDeptName1.setText("NA");

        tblRowDeptBed1.setText("-");

        javax.swing.GroupLayout tblRowOrdersName1Layout = new javax.swing.GroupLayout(tblRowOrdersName1);
        tblRowOrdersName1.setLayout(tblRowOrdersName1Layout);
        tblRowOrdersName1Layout.setHorizontalGroup(
            tblRowOrdersName1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tblRowOrdersName1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tblRowDeptName1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tblRowDeptBed1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        tblRowOrdersName1Layout.setVerticalGroup(
            tblRowOrdersName1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tblRowOrdersName1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tblRowOrdersName1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tblRowDeptBed1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tblRowDeptName1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tblRowDeptName2.setBackground(new java.awt.Color(255, 255, 255));
        tblRowDeptName2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        tblRowDeptName2.setForeground(new java.awt.Color(204, 204, 204));

        tblRowOrderName2.setText("NA");

        tblRowDeptBed2.setText("-");

        javax.swing.GroupLayout tblRowDeptName2Layout = new javax.swing.GroupLayout(tblRowDeptName2);
        tblRowDeptName2.setLayout(tblRowDeptName2Layout);
        tblRowDeptName2Layout.setHorizontalGroup(
            tblRowDeptName2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tblRowDeptName2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tblRowOrderName2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tblRowDeptBed2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        tblRowDeptName2Layout.setVerticalGroup(
            tblRowDeptName2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tblRowDeptName2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tblRowDeptName2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tblRowDeptBed2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tblRowOrderName2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tblRow2.setBackground(new java.awt.Color(255, 255, 255));
        tblRow2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        tblRow2.setForeground(new java.awt.Color(204, 204, 204));

        tblRowDeptName3.setText("NA");

        tblRowDeptBed3.setText("-");

        javax.swing.GroupLayout tblRow2Layout = new javax.swing.GroupLayout(tblRow2);
        tblRow2.setLayout(tblRow2Layout);
        tblRow2Layout.setHorizontalGroup(
            tblRow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tblRow2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tblRowDeptName3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tblRowDeptBed3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        tblRow2Layout.setVerticalGroup(
            tblRow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tblRow2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tblRow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tblRowDeptBed3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tblRowDeptName3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelTopStudentsLayout = new javax.swing.GroupLayout(panelTopStudents);
        panelTopStudents.setLayout(panelTopStudentsLayout);
        panelTopStudentsLayout.setHorizontalGroup(
            panelTopStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTopStudentsLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelTopStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tblRow2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tblRowDeptName2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tblRowOrdersName1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tblHeaderTopStudents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        panelTopStudentsLayout.setVerticalGroup(
            panelTopStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTopStudentsLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(tblHeaderTopStudents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tblRowOrdersName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tblRowDeptName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tblRow2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        boxCountCourse5.setBackground(new java.awt.Color(255, 255, 255));
        boxCountCourse5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        boxCountCourse5.setPreferredSize(new java.awt.Dimension(209, 98));

        lblAppointments.setBackground(new java.awt.Color(255, 255, 255));
        lblAppointments.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblAppointments.setForeground(new java.awt.Color(3, 80, 111));
        lblAppointments.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAppointments.setText("0");

        lblIconCourse5.setBackground(new java.awt.Color(0, 153, 255));
        lblIconCourse5.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblIconCourse5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconCourse5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/courses-dashboard.png"))); // NOI18N

        lblShops1.setForeground(new java.awt.Color(102, 102, 102));
        lblShops1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblShops1.setText("Appointments");

        javax.swing.GroupLayout boxCountCourse5Layout = new javax.swing.GroupLayout(boxCountCourse5);
        boxCountCourse5.setLayout(boxCountCourse5Layout);
        boxCountCourse5Layout.setHorizontalGroup(
            boxCountCourse5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boxCountCourse5Layout.createSequentialGroup()
                .addComponent(lblIconCourse5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(boxCountCourse5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblShops1, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(lblAppointments, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        boxCountCourse5Layout.setVerticalGroup(
            boxCountCourse5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boxCountCourse5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblAppointments, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(lblShops1)
                .addGap(20, 20, 20))
            .addComponent(lblIconCourse5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        boxStudentsCount4.setBackground(new java.awt.Color(255, 255, 255));
        boxStudentsCount4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));

        lblConsultations.setBackground(new java.awt.Color(255, 255, 255));
        lblConsultations.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblConsultations.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConsultations.setText("0");

        lblIconStudent4.setBackground(new java.awt.Color(0, 153, 255));
        lblIconStudent4.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblIconStudent4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconStudent4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/student-dash.png"))); // NOI18N

        lblUsers1.setForeground(new java.awt.Color(102, 102, 102));
        lblUsers1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsers1.setText("Consultations");

        javax.swing.GroupLayout boxStudentsCount4Layout = new javax.swing.GroupLayout(boxStudentsCount4);
        boxStudentsCount4.setLayout(boxStudentsCount4Layout);
        boxStudentsCount4Layout.setHorizontalGroup(
            boxStudentsCount4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boxStudentsCount4Layout.createSequentialGroup()
                .addComponent(lblIconStudent4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(boxStudentsCount4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsers1, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(lblConsultations, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        boxStudentsCount4Layout.setVerticalGroup(
            boxStudentsCount4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boxStudentsCount4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblConsultations, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(lblUsers1)
                .addGap(20, 20, 20))
            .addComponent(lblIconStudent4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        boxStudentsCount5.setBackground(new java.awt.Color(255, 255, 255));
        boxStudentsCount5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));

        lblDoctors.setBackground(new java.awt.Color(0, 153, 255));
        lblDoctors.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblDoctors.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDoctors.setText("0");

        lblIconStudent5.setBackground(new java.awt.Color(0, 153, 255));
        lblIconStudent5.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblIconStudent5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconStudent5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/student-dash.png"))); // NOI18N

        lblOrders3.setForeground(new java.awt.Color(102, 102, 102));
        lblOrders3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOrders3.setText("Doctors");

        javax.swing.GroupLayout boxStudentsCount5Layout = new javax.swing.GroupLayout(boxStudentsCount5);
        boxStudentsCount5.setLayout(boxStudentsCount5Layout);
        boxStudentsCount5Layout.setHorizontalGroup(
            boxStudentsCount5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boxStudentsCount5Layout.createSequentialGroup()
                .addComponent(lblIconStudent5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(boxStudentsCount5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOrders3, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(lblDoctors, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        boxStudentsCount5Layout.setVerticalGroup(
            boxStudentsCount5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boxStudentsCount5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblDoctors, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(lblOrders3)
                .addGap(20, 20, 20))
            .addComponent(lblIconStudent5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        panelTopStudents2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Staff");

        tblHeaderTopStudents1.setBackground(new java.awt.Color(244, 249, 255));
        tblHeaderTopStudents1.setForeground(new java.awt.Color(255, 255, 255));

        lblRowOrdersName2.setText("Name");

        jLabel5.setText("Designation");

        javax.swing.GroupLayout tblHeaderTopStudents1Layout = new javax.swing.GroupLayout(tblHeaderTopStudents1);
        tblHeaderTopStudents1.setLayout(tblHeaderTopStudents1Layout);
        tblHeaderTopStudents1Layout.setHorizontalGroup(
            tblHeaderTopStudents1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tblHeaderTopStudents1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRowOrdersName2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        tblHeaderTopStudents1Layout.setVerticalGroup(
            tblHeaderTopStudents1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tblHeaderTopStudents1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tblHeaderTopStudents1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRowOrdersName2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tblRowOrdersName2.setBackground(new java.awt.Color(255, 255, 255));
        tblRowOrdersName2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        tblRowOrdersName2.setForeground(new java.awt.Color(204, 204, 204));

        tblRowStaffName1.setText("NA");

        tblRowStaffDesig1.setText("-");

        javax.swing.GroupLayout tblRowOrdersName2Layout = new javax.swing.GroupLayout(tblRowOrdersName2);
        tblRowOrdersName2.setLayout(tblRowOrdersName2Layout);
        tblRowOrdersName2Layout.setHorizontalGroup(
            tblRowOrdersName2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tblRowOrdersName2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tblRowStaffName1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tblRowStaffDesig1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        tblRowOrdersName2Layout.setVerticalGroup(
            tblRowOrdersName2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tblRowOrdersName2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tblRowOrdersName2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tblRowStaffDesig1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tblRowStaffName1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tblRow6.setBackground(new java.awt.Color(255, 255, 255));
        tblRow6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        tblRow6.setForeground(new java.awt.Color(204, 204, 204));

        tblRowStaffName2.setText("NA");

        tblRowStaffDesig2.setText("-");

        javax.swing.GroupLayout tblRow6Layout = new javax.swing.GroupLayout(tblRow6);
        tblRow6.setLayout(tblRow6Layout);
        tblRow6Layout.setHorizontalGroup(
            tblRow6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tblRow6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tblRowStaffName2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tblRowStaffDesig2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        tblRow6Layout.setVerticalGroup(
            tblRow6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tblRow6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tblRow6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tblRowStaffDesig2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tblRowStaffName2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tblRow7.setBackground(new java.awt.Color(255, 255, 255));
        tblRow7.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        tblRow7.setForeground(new java.awt.Color(204, 204, 204));

        tblRowStaffName3.setText("NA");

        tblRowStaffDesig3.setText("-");

        javax.swing.GroupLayout tblRow7Layout = new javax.swing.GroupLayout(tblRow7);
        tblRow7.setLayout(tblRow7Layout);
        tblRow7Layout.setHorizontalGroup(
            tblRow7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tblRow7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tblRowStaffName3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tblRowStaffDesig3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        tblRow7Layout.setVerticalGroup(
            tblRow7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tblRow7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tblRow7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tblRowStaffDesig3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tblRowStaffName3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelTopStudents2Layout = new javax.swing.GroupLayout(panelTopStudents2);
        panelTopStudents2.setLayout(panelTopStudents2Layout);
        panelTopStudents2Layout.setHorizontalGroup(
            panelTopStudents2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTopStudents2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelTopStudents2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tblRow7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tblRow6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tblRowOrdersName2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tblHeaderTopStudents1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        panelTopStudents2Layout.setVerticalGroup(
            panelTopStudents2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTopStudents2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(tblHeaderTopStudents1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tblRowOrdersName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tblRow6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tblRow7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelTopStudents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(boxStudentsCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(boxCountCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(boxStudentsCount2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(panelTopStudents2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(boxStudentsCount5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(boxCountCourse5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(boxStudentsCount4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(60, 60, 60))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {boxCountCourse, boxStudentsCount, boxStudentsCount2});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {boxCountCourse5, boxStudentsCount4, boxStudentsCount5});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boxCountCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxStudentsCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxStudentsCount2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boxCountCourse5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxStudentsCount5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxStudentsCount4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTopStudents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelTopStudents2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel boxCountCourse;
    private javax.swing.JPanel boxCountCourse5;
    private javax.swing.JPanel boxStudentsCount;
    private javax.swing.JPanel boxStudentsCount2;
    private javax.swing.JPanel boxStudentsCount4;
    private javax.swing.JPanel boxStudentsCount5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblAppointments;
    private javax.swing.JLabel lblBeds;
    private javax.swing.JLabel lblConsultations;
    private javax.swing.JLabel lblDept;
    private javax.swing.JLabel lblDoctors;
    private javax.swing.JLabel lblIconCourse;
    private javax.swing.JLabel lblIconCourse5;
    private javax.swing.JLabel lblIconStudent;
    private javax.swing.JLabel lblIconStudent2;
    private javax.swing.JLabel lblIconStudent4;
    private javax.swing.JLabel lblIconStudent5;
    private javax.swing.JLabel lblOrders1;
    private javax.swing.JLabel lblOrders3;
    private javax.swing.JLabel lblRowOrdersName1;
    private javax.swing.JLabel lblRowOrdersName2;
    private javax.swing.JLabel lblShops;
    private javax.swing.JLabel lblShops1;
    private javax.swing.JLabel lblStaff;
    private javax.swing.JLabel lblUsers;
    private javax.swing.JLabel lblUsers1;
    private javax.swing.JPanel panelTopStudents;
    private javax.swing.JPanel panelTopStudents2;
    private javax.swing.JPanel tblHeaderTopStudents;
    private javax.swing.JPanel tblHeaderTopStudents1;
    private javax.swing.JPanel tblRow2;
    private javax.swing.JPanel tblRow6;
    private javax.swing.JPanel tblRow7;
    private javax.swing.JLabel tblRowDeptBed1;
    private javax.swing.JLabel tblRowDeptBed2;
    private javax.swing.JLabel tblRowDeptBed3;
    private javax.swing.JLabel tblRowDeptName1;
    private javax.swing.JPanel tblRowDeptName2;
    private javax.swing.JLabel tblRowDeptName3;
    private javax.swing.JLabel tblRowOrderName2;
    private javax.swing.JPanel tblRowOrdersName1;
    private javax.swing.JPanel tblRowOrdersName2;
    private javax.swing.JLabel tblRowStaffDesig1;
    private javax.swing.JLabel tblRowStaffDesig2;
    private javax.swing.JLabel tblRowStaffDesig3;
    private javax.swing.JLabel tblRowStaffName1;
    private javax.swing.JLabel tblRowStaffName2;
    private javax.swing.JLabel tblRowStaffName3;
    // End of variables declaration//GEN-END:variables

    private void setData() {
        HospitalDepartmentDirectory hdd = hospital.getDepartmentDirectory();

        if (hdd != null) {

            lblDept.setText(String.valueOf(hdd.getDepartmentList().size()));

            int staff = 0, beds = 0, consultation = 0, deptCount = 1, staffCount = 1, doctors = 0;

            int appointments = 0;

            if (hdd.getDepartmentList() != null) {

                for (HospitalDepartment hd : hdd.getDepartmentList()) {

                    beds += hd.getNumberOfBeds();

                    switch (deptCount) {
                        case 1:
                            tblRowDeptName1.setText(hd.getDepartmentName());
                            tblRowDeptBed1.setText(String.valueOf(hd.getNumberOfBeds()));
                            deptCount++;
                            break;
                        case 2:
                            tblRowOrderName2.setText(hd.getDepartmentName());
                            tblRowDeptBed2.setText(String.valueOf(hd.getNumberOfBeds()));
                            deptCount++;
                            break;
                        case 3:
                            tblRowDeptName3.setText(hd.getDepartmentName());
                            tblRowDeptBed3.setText(String.valueOf(hd.getNumberOfBeds()));
                            deptCount++;
                            break;
                        default:
                            break;
                    }

                    if (hd.getStaffDirectory() != null && hd.getStaffDirectory().getStaffList() != null) {
                        staff += hd.getStaffDirectory().getStaffList().size();
                        for (Staff s : hd.getStaffDirectory().getStaffList()) {
                            consultation += s.getConsultationDirectory().getSession().size();

                            if (s.getDesignation().equalsIgnoreCase("DOCTOR")) {
                                doctors++;
                            }

                            if (ecosystem.getWorkQueue() != null
                                    && ecosystem.getWorkQueue().getStaffRequestList1(s, "USER-ORDER") != null) {
                                appointments = ecosystem.getWorkQueue().getStaffRequestList1(s, "USER-ORDER").size();
                            }

                            switch (staffCount) {
                                case 1:
                                    tblRowStaffName1.setText(s.getName());
                                    tblRowStaffDesig1.setText(s.getDesignation());

                                    staffCount++;
                                    break;
                                case 2:
                                    tblRowStaffName2.setText(s.getName());
                                    tblRowStaffDesig2.setText(s.getDesignation());
                                    staffCount++;
                                    break;
                                case 3:
                                    tblRowStaffName3.setText(s.getName());
                                    tblRowStaffDesig3.setText(s.getDesignation());
                                    staffCount++;
                                    break;
                                default:
                                    break;
                            }
                        }
                    }
                }

                lblBeds.setText(String.valueOf(beds));
                lblStaff.setText(String.valueOf(staff));
                lblConsultations.setText(String.valueOf(consultation));
                lblDoctors.setText(String.valueOf(doctors));
                lblAppointments.setText(String.valueOf(appointments));
            }
        }
    }
}
